----Generated by Ebean----
-- apply changes
create table sys_resource (
  id                            bigint auto_increment not null,
  resource_name                 varchar(20) not null comment 'resource name',
  url                           varchar(50) not null comment 'resource url',
  url_status                    integer(1) not null comment 'url status',
  remark                        varchar(200) comment 'remark',
  record_modification_version   bigint not null,
  when_created                  datetime(6) not null,
  when_modified                 datetime(6) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  deleted                       tinyint(1) default 0 not null,
  constraint pk_sys_resource primary key (id)
);

create table sys_role (
  id                            bigint auto_increment not null,
  role_name                     varchar(20) not null comment 'role name',
  role_status                   integer(1) not null comment 'role status',
  remark                        varchar(100) comment 'remark',
  record_modification_version   bigint not null,
  when_created                  datetime(6) not null,
  when_modified                 datetime(6) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  deleted                       tinyint(1) default 0 not null,
  constraint pk_sys_role primary key (id)
);

create table sys_role_resource (
  id                            bigint auto_increment not null,
  role_id                       bigint(19) not null comment 'role id',
  resource_id                   bigint(19) not null comment 'resource id',
  record_modification_version   bigint not null,
  when_created                  datetime(6) not null,
  when_modified                 datetime(6) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  deleted                       tinyint(1) default 0 not null,
  constraint pk_sys_role_resource primary key (id)
);

create table sys_user_role (
  id                            bigint auto_increment not null,
  user_id                       bigint not null comment 'user id',
  role_id                       bigint not null comment 'role id',
  record_modification_version   bigint not null,
  when_created                  datetime(6) not null,
  when_modified                 datetime(6) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  deleted                       tinyint(1) default 0 not null,
  constraint pk_sys_user_role primary key (id)
);

create table user_info (
  id                            bigint auto_increment not null,
  username                      varchar(50) not null comment 'username',
  telephone                     varchar(255) comment 'telephone',
  gender                        integer(2) comment 'gender',
  email                         varchar(255) comment 'email',
  user_status                   integer comment 'user''s status info',
  password                      varchar(255),
  record_modification_version   bigint not null,
  when_created                  datetime(6) not null,
  when_modified                 datetime(6) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  deleted                       tinyint(1) default 0 not null,
  constraint pk_user_info primary key (id)
);

-- foreign keys and indices
create index ix_sys_user_role_user_id on sys_user_role (user_id);
alter table sys_user_role add constraint fk_sys_user_role_user_id foreign key (user_id) references user_info (id) on delete restrict on update restrict;

create index ix_sys_user_role_role_id on sys_user_role (role_id);
alter table sys_user_role add constraint fk_sys_user_role_role_id foreign key (role_id) references sys_role (id) on delete restrict on update restrict;

