----Generated by Ebean----
-- apply changes
create table sys_resource (
  id                            bigint auto_increment not null,
  parent_id                     bigint comment 'parent id',
  resource_name                 varchar(20) not null comment 'resource name',
  resource_type                 integer(20) not null comment 'resource type, 1:dir,2:menu,3:button',
  url                           varchar(50) comment 'resource url',
  resource_status               integer(1) not null comment 'resource status, 1:normal,0:disabled',
  permission                    varchar(100) comment 'permission',
  remark                        varchar(200) comment 'remark',
  record_modification_version   bigint not null,
  when_created                  datetime(6) not null,
  when_modified                 datetime(6) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  deleted                       tinyint(1) default 0 not null,
  constraint pk_sys_resource primary key (id)
);

create table sys_role (
  id                            bigint auto_increment not null,
  role_name                     varchar(20) not null comment 'role name',
  role_status                   integer(1) not null comment 'role status',
  remark                        varchar(100) comment 'remark',
  record_modification_version   bigint not null,
  when_created                  datetime(6) not null,
  when_modified                 datetime(6) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  deleted                       tinyint(1) default 0 not null,
  constraint pk_sys_role primary key (id)
);

create table sys_role_resource (
  id                            bigint auto_increment not null,
  sys_role_id                   bigint comment 'role id',
  sys_resource_id               bigint comment 'resource id',
  record_modification_version   bigint not null,
  when_created                  datetime(6) not null,
  when_modified                 datetime(6) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  deleted                       tinyint(1) default 0 not null,
  constraint pk_sys_role_resource primary key (id)
);

create table sys_user_role (
  id                            bigint auto_increment not null,
  user_id                       bigint not null comment 'user id',
  role_id                       bigint not null comment 'role id',
  record_modification_version   bigint not null,
  when_created                  datetime(6) not null,
  when_modified                 datetime(6) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  deleted                       tinyint(1) default 0 not null,
  constraint pk_sys_user_role primary key (id)
);

create table user_info (
  id                            bigint auto_increment not null,
  username                      varchar(50) not null comment 'username',
  telephone                     varchar(255) comment 'telephone',
  gender                        integer(2) comment 'gender',
  email                         varchar(255) comment 'email',
  user_status                   integer comment 'user''s status info',
  password                      varchar(255),
  record_modification_version   bigint not null,
  when_created                  datetime(6) not null,
  when_modified                 datetime(6) not null,
  who_created                   varchar(255) not null,
  who_modified                  varchar(255) not null,
  deleted                       tinyint(1) default 0 not null,
  constraint pk_user_info primary key (id)
);

-- foreign keys and indices
create index ix_sys_resource_parent_id on sys_resource (parent_id);

create index ix_sys_role_resource_sys_role_id on sys_role_resource (sys_role_id);

create index ix_sys_role_resource_sys_resource_id on sys_role_resource (sys_resource_id);

create index ix_sys_user_role_user_id on sys_user_role (user_id);

create index ix_sys_user_role_role_id on sys_user_role (role_id);
