----Generated by Ebean----
-- apply alter tables
alter table sys_resource add column deleted tinyint(1) default 0 not null;
alter table sys_role add column deleted tinyint(1) default 0 not null;
alter table sys_role_resource add column deleted tinyint(1) default 0 not null;
alter table sys_user_role add column deleted tinyint(1) default 0 not null;
alter table user_info add column deleted tinyint(1) default 0 not null;
