----Generated by Ebean----
-- apply alter tables
alter table sys_resource add column parent_id bigint;
alter table sys_resource add column resource_type integer(20) not null;
alter table sys_resource add column resource_status integer(1) not null;
alter table sys_resource add column permission varchar(100);
-- foreign keys and indices
create index ix_sys_resource_parent_id on sys_resource (parent_id);
alter table sys_resource add constraint fk_sys_resource_parent_id foreign key (parent_id) references sys_resource (id) on delete restrict on update restrict;

