spring:
  datasource:
    #    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: mysql
    password: mysql
    url: jdbc:mysql://127.0.0.1:3306/douding
    hikari:
      # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 10
      # 连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 2000
      pool-name: ebean-hikari
      auto-commit: false
      # 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 1800000
      validation-timeout: 1000
      # 保活频率， 30s 最小值
      keepalive-time: 30000

