server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  undertow:
    threads:
      io: 16
      worker: 120
    buffer-size: 2048
    direct-buffers: true

ebean:
  packages: com.doubao.douding
  migration:
    run: true
  debug:
    sql: true
    lazyload: false
    logging:
      logfilesharing: all
      directory: logs
      iud: sql
      query: sql
      sqlquery: sql
      txnCommit: none
#  mappingLocations: classpath:/ebean-xml-mappings
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  api-docs:
    enabled: true
  swagger-ui:
    persistAuthorization: true
  data:
    redis:
      host: 39.100.182.241
      port: 6379
      database: 0
      timeout: 3000
      connectTimeout: 5000
      lettuce:
        pool:
          min-idle: 5
          max-idle: 10
          max-active: 100
          max-wait: 2000

jwt:
  private.key: classpath:app.private
  public.key: classpath:app.public
  # 60s * 60 = 1 hour
  expiry: 3600
  # 10 hours
  refreshExpiry: 36000

 # 39.100.182.241